name: CD
on:
  workflow_call:

jobs:
  upload-image:
     runs-on: ubuntu-latest
     environment: production
     
     env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

     steps:
       - name: Hacer pull de la imagen de Docker
         run: |
          docker pull $DOCKER_USERNAME/sample-angular-app:0.0.0
          
       - name: Desplegar
         run: |
          docker run -d -p 8080:8080  $DOCKER_USERNAME/sample-angular-app:0.0.0

       - name: Verificar si el contenedor est√° corriendo
         run: docker ps

       - name: Verificar respuesta de la app
         run: |
           sleep 40
           curl http://localhost:8080


        
